# -*- coding: utf-8 -*-

from typing import Final

CVPM_NO_DOTENV: Final[str] = "CVPM_NO_DOTENV"
CVPM_DOTENV_PATH: Final[str] = "CVPM_NO_DOTENV"

CVPM_COLORED_LOGGING: Final[str] = "CVPM_COLORED_LOGGING"
CVPM_SIMPLE_LOGGING: Final[str] = "CVPM_SIMPLE_LOGGING"

CVPM_LOGGING_STEP: Final[str] = "CVPM_LOGGING_STEP"
CVPM_LOGGING_SEVERITY: Final[str] = "CVPM_LOGGING_SEVERITY"

CVPM_HOME: Final[str] = "CVPM_HOME"

CVPM_USE_UVLOOP: Final[str] = "CVPM_USE_UVLOOP"
CVPM_DEBUG: Final[str] = "CVPM_DEBUG"
CVPM_VERBOSE: Final[str] = "CVPM_VERBOSE"

CVPM_AGENT_SLUG: Final[str] = "CVPM_AGENT_SLUG"
CVPM_AGENT_TOKEN: Final[str] = "CVPM_AGENT_TOKEN"
